name: "Create Image"

on:
  push:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Download RaspPi OS"
      run: |
        wget https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2022-09-26/2022-09-22-raspios-bullseye-arm64-lite.img.xz
        unxz *.img.xz
        mv *.img input.img

    - name: "Run CustoPiZer"
      uses: OctoPrint/CustoPiZer@main
      with:
        workspace: "${{ github.workspace }}"
        scripts:  "${{ github.workspace }}/scripts"
        config: "${{ github.workspace }}/config.local"
    
    - name: "Rename image"
      run: |
        mv output.img HAL_RPI.img

    - name: "Upload image"
      uses: actions/upload-artifact@v3
      with:
        name: HAL_RPI
        path: HAL_RPI.img
